preset: laravel

enabled:
    - concat_with_spaces

disabled:
    - phpdoc_no_package
    - concat_without_spaces
    - simplified_null_return

finder:
    not-path:
        - "public/index.php"
        - "server.php"
